version: '3.8'

services:
  frontend:
    image: ecom-client-app
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: ecom-server-app
    build:
      context: .
      dockerfile: server/Dockerfile
    # expose the port to the host machine only when you are developing
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/ecom-web-app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    # expose the port to the host machine only when you are developing
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
